apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
- namespace.yaml
- postgresql-config.yaml
- postgresql-pvc.yaml
- postgresql-service.yaml
- postgresql-deployment.yaml
- postgresql-networkpolicy.yaml