apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
- namespace.yaml
- vaultwarden-config.yaml
- vaultwarden-pvc.yaml
- vaultwarden-service.yaml
- vaultwarden-deployment.yaml
- vaultwarden-ingressroute.yaml